http:
  port: 8080
admin:
  port: 5000
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/api/**'
  user:
    host: localhost
    paths: '/user/login'
serviceEndpoints:
  backend:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  user:
    apiEndpoints:
      - user
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: backend 
              changeOrigin: true
